// <auto-generated />
using System;
using Assessment.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assessment.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assessment.Api.Domain.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorUserId", "OrganizationId")
                        .HasDatabaseName("ix_audit_events_actor_user_id_organization_id");

                    b.HasIndex("OrganizationId", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_organization_id_entity_id_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Assessment.Api.Domain.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_cost");

                    b.Property<decimal>("ApprovalThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("approval_threshold");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_requests");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_maintenance_requests_id_organization_id");

                    b.HasIndex("RequestedById", "OrganizationId")
                        .HasDatabaseName("ix_maintenance_requests_requested_by_id_organization_id");

                    b.HasIndex("SiteId", "OrganizationId")
                        .HasDatabaseName("ix_maintenance_requests_site_id_organization_id");

                    b.HasIndex("OrganizationId", "SiteId", "CompletedAt")
                        .HasDatabaseName("ix_maintenance_requests_spend_report")
                        .HasFilter("status = 'Completed'");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OrganizationId", "SiteId", "CompletedAt"), new[] { "ActualCost" });

                    b.HasIndex("OrganizationId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_maintenance_requests_organization_id_status_created_at");

                    b.ToTable("maintenance_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_requests_actual_cost", "actual_cost IS NULL OR actual_cost > 0");

                            t.HasCheckConstraint("ck_requests_completed_has_actual", "status <> 'Completed' OR (actual_cost IS NOT NULL AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_requests_estimated_cost", "estimated_cost > 0");

                            t.HasCheckConstraint("ck_requests_status", "status IN ('Raised', 'PendingApproval', 'Approved', 'Rejected', 'Completed')");

                            t.HasCheckConstraint("ck_requests_threshold", "approval_threshold >= 0");
                        });
                });

            modelBuilder.Entity("Assessment.Api.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ApprovalThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(10000m)
                        .HasColumnName("approval_threshold");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_threshold", "approval_threshold >= 0");
                        });
                });

            modelBuilder.Entity("Assessment.Api.Domain.RequestRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_comment");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("PreviousRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_revision_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_request_revisions");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_request_revisions_id_organization_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_request_revisions_organization_id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_request_revisions_one_pending")
                        .HasFilter("outcome = 'Pending'");

                    b.HasIndex("DecidedById", "OrganizationId")
                        .HasDatabaseName("ix_request_revisions_decided_by_id_organization_id");

                    b.HasIndex("PreviousRevisionId", "OrganizationId")
                        .HasDatabaseName("ix_request_revisions_previous_revision_id_organization_id");

                    b.HasIndex("RequestId", "OrganizationId")
                        .HasDatabaseName("ix_request_revisions_request_id_organization_id");

                    b.HasIndex("RequestId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_request_revisions_request_id_sequence");

                    b.HasIndex("SubmittedById", "OrganizationId")
                        .HasDatabaseName("ix_request_revisions_submitted_by_id_organization_id");

                    b.ToTable("request_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_revisions_amount", "amount > 0");

                            t.HasCheckConstraint("ck_revisions_kind", "kind IN ('Initial', 'Edit', 'ActualCost')");

                            t.HasCheckConstraint("ck_revisions_not_self_decided", "decided_by_id IS NULL OR decided_by_id <> submitted_by_id");

                            t.HasCheckConstraint("ck_revisions_outcome", "outcome IN ('Pending', 'AutoApproved', 'Approved', 'Rejected', 'Superseded')");
                        });
                });

            modelBuilder.Entity("Assessment.Api.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_roles_id_organization_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_organization_id_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Assessment.Api.Domain.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_sites_id_organization_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_organization_id_name");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Assessment.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_users_id_organization_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.HasIndex("RoleId", "OrganizationId")
                        .HasDatabaseName("ix_users_role_id_organization_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_lowercase", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("Assessment.Api.Domain.AuditEvent", b =>
                {
                    b.HasOne("Assessment.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_organizations_organization_id");

                    b.HasOne("Assessment.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_users_actor_user_id_organization_id");
                });

            modelBuilder.Entity("Assessment.Api.Domain.MaintenanceRequest", b =>
                {
                    b.HasOne("Assessment.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_organizations_organization_id");

                    b.HasOne("Assessment.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedById", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_users_requested_by_id_organization_id");

                    b.HasOne("Assessment.Api.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_sites_site_id_organization_id");
                });

            modelBuilder.Entity("Assessment.Api.Domain.RequestRevision", b =>
                {
                    b.HasOne("Assessment.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_revisions_organizations_organization_id");

                    b.HasOne("Assessment.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedById", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_request_revisions_users_decided_by_id_organization_id");

                    b.HasOne("Assessment.Api.Domain.RequestRevision", null)
                        .WithMany()
                        .HasForeignKey("PreviousRevisionId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_request_revisions_request_revisions_previous_revision_id_or");

                    b.HasOne("Assessment.Api.Domain.MaintenanceRequest", null)
                        .WithMany("Revisions")
                        .HasForeignKey("RequestId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_revisions_maintenance_requests_request_id_organizat");

                    b.HasOne("Assessment.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedById", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_revisions_users_submitted_by_id_organization_id");
                });

            modelBuilder.Entity("Assessment.Api.Domain.Role", b =>
                {
                    b.HasOne("Assessment.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_organizations_organization_id");
                });

            modelBuilder.Entity("Assessment.Api.Domain.Site", b =>
                {
                    b.HasOne("Assessment.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sites_organizations_organization_id");
                });

            modelBuilder.Entity("Assessment.Api.Domain.User", b =>
                {
                    b.HasOne("Assessment.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");

                    b.HasOne("Assessment.Api.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id_organization_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Assessment.Api.Domain.MaintenanceRequest", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
